<script setup lang="ts">
import { Document, Money } from "@element-plus/icons-vue";
import PrototypePageShell from "~/components/hrms/PrototypePageShell.vue";
import { ROUTES } from "~/constants/routes";

const stats = [
  { label: "Latest Payslip", value: "Ready", hint: "Prototype payroll output" },
  { label: "Payroll Month", value: "Apr 2026", hint: "Sample month" },
  { label: "Net Pay", value: "$2,400", hint: "Demo figure only" },
  { label: "OT Included", value: "Yes", hint: "Approved overtime is present" },
];

const actions = [
  {
    title: "Payroll Dashboard",
    description: "Return to the payroll workspace.",
    route: ROUTES.PAYROLL_MANAGER.DASHBOARD,
    icon: Money,
    color: "#0f766e",
  },
  {
    title: "Leave History",
    description: "Cross-reference leave impact on payroll.",
    route: ROUTES.EMPLOYEE.LEAVE_HISTORY,
    icon: Document,
    color: "#2563eb",
  },
  {
    title: "Attendance History",
    description: "Review attendance records before pay runs.",
    route: ROUTES.EMPLOYEE.ATTENDANCE_HISTORY,
    icon: Document,
    color: "#d97706",
  },
];

const sections = [
  {
    title: "Payslip details",
    items: ["Basic salary", "Overtime earnings", "Deductions", "Net pay"],
  },
  {
    title: "Backend alignment",
    items: ["Payroll manager run output", "Employee payslip viewing route"],
  },
];
</script>

<template>
  <PrototypePageShell
    title="Employee Payslips"
    description="Prototype view for employee payslips generated by the payroll workflow."
    back-path="/employee/dashboard"
    badge="Payslips"
    accent="#0f766e"
    :stats="stats"
    :actions="actions"
    :sections="sections"
  />
</template>
